export enum PLAYER_CONSTANTS {
  LOGO = 'logo',
  PLAY = 'PLAY',
  PAUSE = 'PAUSE',
  INCREASE = 'INCREASE',
  DECREASE = 'DECREASE',
  VOLUME_UP = 'VOLUME_UP',
  VOLUME_DOWN = 'VOLUME_DOWN',
  FULL_SCREEN = 'FULL_SCREEN',
}
