import type { PLAYER_CONSTANTS } from 'features/player/constants/player.constants'

export type PLAYER_GESTURE_TYPE =
  | PLAYER_CONSTANTS.PLAY
  | PLAYER_CONSTANTS.PAUSE
  | PLAYER_CONSTANTS.DECREASE
  | PLAYER_CONSTANTS.INCREASE
  | PLAYER_CONSTANTS.VOLUME_UP
  | PLAYER_CONSTANTS.VOLUME_DOWN
  | PLAYER_CONSTANTS.FULL_SCREEN
